-- MySQL Script generated by MySQL Workbench
-- sab 11 nov 2017 18:10:20 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HuntingTheBismarck
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HuntingTheBismarck
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HuntingTheBismarck` DEFAULT CHARACTER SET utf8 ;
USE `HuntingTheBismarck` ;

-- -----------------------------------------------------
-- Table `HuntingTheBismarck`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HuntingTheBismarck`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `score` INT NOT NULL DEFAULT 0,
  `max_score` INT NOT NULL DEFAULT 0,
  `vinte` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
